version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
      - pip install mkdocs-material
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --only doc

mkdocs:
  configuration: mkdocs.yml


