version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      - poetry install --with doc

mkdocs:
  configuration: mkdocs.yml


