site_name: Criptografia RSA
repo_url: https://github.com/PHBueno/RSA
repo_name: PHBueno/RSA

markdown_extensions: 
  - attr_list
  - admonition
  - pymdownx.tasklist

theme: 
  name: material
  language: pt-BR

plugins: 
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [rsa]

extra: 
  commands:
    run: rsa
